global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'aegir'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['aegir:8443']
    metrics_path: '/metrics'
